Repository BUTTERFLY-CODE-NEAR/Butterfly_BE, pull requests merged in 2024-10, with the labels that each got.

#156 refactor: 요청 시 플랫폼 포힘하게끔 로직 수정
  src/main/java/com/codenear/butterfly/auth/application/AuthService.java
  src/main/java/com/codenear/butterfly/auth/application/email/EmailLoginService.java
Labels: 🛠️ Refactor

#160 157 refactor 권한 정보 변경 리팩토링
  src/main/java/com/codenear/butterfly/auth/application/AuthService.java
  src/main/java/com/codenear/butterfly/auth/application/JwtService.java
  src/main/java/com/codenear/butterfly/auth/application/OauthService.java
  src/main/java/com/codenear/butterfly/auth/application/email/CustomUserDetailsService.java
  src/main/java/com/codenear/butterfly/auth/application/email/EmailRegisterService.java
  src/main/java/com/codenear/butterfly/auth/domain/JwtRefresh.java
  src/main/java/com/codenear/butterfly/auth/domain/JwtRefreshRepository.java
  src/main/java/com/codenear/butterfly/auth/domain/dto/CustomUserDetails.java
  src/main/java/com/codenear/butterfly/auth/util/JwtUtil.java
  src/main/java/com/codenear/butterfly/global/config/SecurityConfig.java
  src/main/java/com/codenear/butterfly/global/filter/JwtFilter.java
Labels: 🛠️ Refactor

#163 162 스프링 시큐리티 사용자 정보 저장 방식 변경
  src/main/java/com/codenear/butterfly/member/application/MemberService.java
  src/main/java/com/codenear/butterfly/member/domain/dto/MemberDTO.java
  src/main/java/com/codenear/butterfly/member/presentation/MemberController.java
  src/main/java/com/codenear/butterfly/member/presentation/swagger/MemberControllerSwagger.java
  src/main/java/com/codenear/butterfly/point/application/PointService.java
  src/main/java/com/codenear/butterfly/point/domain/PointRepository.java
Labels: 🛠️ Refactor

#165 feat: Redis 설정 추가 (#164)
  src/main/java/com/codenear/butterfly/ButterflyApplication.java
  src/main/java/com/codenear/butterfly/global/config/RedisConfig.java
Labels: 🚀 Feat

#167 refactor: 검색 API 새로운 객체로 리팩토링 (#166)
  src/main/java/com/codenear/butterfly/search/application/SearchService.java
  src/main/java/com/codenear/butterfly/search/presentation/SearchController.java
  src/main/java/com/codenear/butterfly/search/presentation/SearchControllerSwagger.java
Labels: 🛠️ Refactor

#170 168 고객 문의 api 새로운 객체로 리팩토링
  src/main/java/com/codenear/butterfly/global/filter/JwtFilter.java
  src/main/java/com/codenear/butterfly/member/application/MemberService.java
  src/main/java/com/codenear/butterfly/support/application/InquiryService.java
  src/main/java/com/codenear/butterfly/support/domain/InquiryRepository.java
  src/main/java/com/codenear/butterfly/support/presentation/InquiryController.java
  src/main/java/com/codenear/butterfly/support/presentation/InquiryControllerSwagger.java
Labels: 🛠️ Refactor

#171 refactor: 상품 Api 새로운 객체로 리팩토링
  src/main/java/com/codenear/butterfly/product/application/FavoriteService.java
  src/main/java/com/codenear/butterfly/product/application/ProductViewService.java
  src/main/java/com/codenear/butterfly/product/presentation/ProductController.java
  src/main/java/com/codenear/butterfly/product/presentation/ProductControllerSwagger.java
Labels: 🛠️ Refactor

#173 172 code near 로그인회원가입 리팩토링
  src/main/java/com/codenear/butterfly/auth/application/email/EmailLoginService.java
  src/main/java/com/codenear/butterfly/auth/application/email/EmailRegisterService.java
  src/main/java/com/codenear/butterfly/global/exception/ErrorCode.java
Labels: 🛠️ Refactor

#175 fix: 상품 최대 구매 갯수 대문자 표기 핫픽스
  src/main/java/com/codenear/butterfly/product/domain/dto/ProductDetailDTO.java
  src/main/java/com/codenear/butterfly/product/domain/dto/ProductViewDTO.java
Labels: 🐞 Bug

#182 181 상품 구매
  src/main/java/com/codenear/butterfly/kakaoPay/application/SinglePaymentService.java
  src/main/java/com/codenear/butterfly/kakaoPay/presentation/SinglePayController.java
  src/main/java/com/codenear/butterfly/kakaoPay/presentation/SinglePayControllerSwagger.java
Labels: 🚀 Feat

#185 fix: 파라미터 변경 및 인터페이스 안쓰는 부분 정리 (#184)
  src/main/java/com/codenear/butterfly/search/presentation/SearchControllerSwagger.java
Labels: 🐞 Bug

#186 177 주소 추가, 조회, 수정 기능
  src/main/java/com/codenear/butterfly/address/application/AddressService.java
  src/main/java/com/codenear/butterfly/address/domain/Address.java
  src/main/java/com/codenear/butterfly/address/domain/AddressRepository.java
  src/main/java/com/codenear/butterfly/address/domain/dto/AddressCreateDTO.java
  src/main/java/com/codenear/butterfly/address/domain/dto/AddressResponseDTO.java
  src/main/java/com/codenear/butterfly/address/domain/dto/AddressUpdateDTO.java
  src/main/java/com/codenear/butterfly/address/exception/AddressException.java
  src/main/java/com/codenear/butterfly/address/presentation/AddressController.java
  src/main/java/com/codenear/butterfly/address/presentation/AddressControllerSwagger.java
  src/main/java/com/codenear/butterfly/global/config/SwaggerConfig.java
  src/main/java/com/codenear/butterfly/member/domain/Member.java
Labels: 🚀 Feat

#189 188 refactor 찜 목록 상품 반환 api 리팩토링
  src/main/java/com/codenear/butterfly/global/exception/ErrorCode.java
  src/main/java/com/codenear/butterfly/product/application/FavoriteService.java
  src/main/java/com/codenear/butterfly/product/application/ProductViewService.java
  src/main/java/com/codenear/butterfly/product/domain/Option.java
  src/main/java/com/codenear/butterfly/product/domain/Product.java
  src/main/java/com/codenear/butterfly/product/domain/dto/OptionDTO.java
  src/main/java/com/codenear/butterfly/product/domain/dto/ProductDetailDTO.java
  src/main/java/com/codenear/butterfly/product/domain/dto/ProductViewDTO.java
  src/main/java/com/codenear/butterfly/product/presentation/ProductController.java
  src/main/java/com/codenear/butterfly/product/presentation/ProductControllerSwagger.java
Labels: 🛠️ Refactor

#190 187 주소 상세 보기 기능
  src/main/java/com/codenear/butterfly/address/application/AddressService.java
  src/main/java/com/codenear/butterfly/address/domain/dto/AddressResponseDTO.java
  src/main/java/com/codenear/butterfly/address/presentation/AddressController.java
  src/main/java/com/codenear/butterfly/address/presentation/AddressControllerSwagger.java
Labels: 🚀 Feat

#192 refactor: 찜 목록 DTO 반환
  src/main/java/com/codenear/butterfly/product/application/FavoriteService.java
Labels: 🛠️ Refactor

#193 191 메인 주소 변경 기능
  src/main/java/com/codenear/butterfly/address/application/AddressService.java
  src/main/java/com/codenear/butterfly/address/domain/Address.java
  src/main/java/com/codenear/butterfly/address/presentation/AddressController.java
  src/main/java/com/codenear/butterfly/address/presentation/AddressControllerSwagger.java
Labels: 🚀 Feat

#195 194 주소 삭제 기능
  src/main/java/com/codenear/butterfly/address/application/AddressService.java
  src/main/java/com/codenear/butterfly/address/presentation/AddressController.java
  src/main/java/com/codenear/butterfly/address/presentation/AddressControllerSwagger.java
Labels: 🚀 Feat

#196 181 상품 구매
  src/main/java/com/codenear/butterfly/kakaoPay/application/SinglePaymentService.java
  src/main/java/com/codenear/butterfly/kakaoPay/domain/Amount.java
  src/main/java/com/codenear/butterfly/kakaoPay/domain/CardInfo.java
  src/main/java/com/codenear/butterfly/kakaoPay/domain/SinglePayment.java
  src/main/java/com/codenear/butterfly/kakaoPay/domain/dto/PaymentRequestDTO.java
  src/main/java/com/codenear/butterfly/kakaoPay/domain/dto/kakao/ApproveResponseDTO.java
  src/main/java/com/codenear/butterfly/kakaoPay/domain/repository/SinglePaymentRepository.java
  src/main/java/com/codenear/butterfly/product/presentation/ProductController.java
Labels: 🚀 Feat, 🛠️ Refactor

#198 feat: 유저 정보 이메일, 쿠폰 추가 (#197)
  src/main/java/com/codenear/butterfly/member/application/MemberService.java
  src/main/java/com/codenear/butterfly/member/domain/dto/MemberInfoDTO.java
Labels: 🚀 Feat

#201 199 feat 마케팅 수신 동의 변동 및 저장 추가
  src/main/java/com/codenear/butterfly/consent/application/ConsentService.java
  src/main/java/com/codenear/butterfly/consent/domain/Consent.java
  src/main/java/com/codenear/butterfly/consent/domain/ConsentRepository.java
  src/main/java/com/codenear/butterfly/consent/domain/ConsentType.java
  src/main/java/com/codenear/butterfly/consent/dto/ConsentInfoResponseDTO.java
  src/main/java/com/codenear/butterfly/consent/dto/ConsentSingleResponseDTO.java
  src/main/java/com/codenear/butterfly/consent/presentation/ConsentController.java
  src/main/java/com/codenear/butterfly/consent/presentation/ConsentControllerSwagger.java
  src/main/java/com/codenear/butterfly/global/config/SwaggerConfig.java
  src/main/java/com/codenear/butterfly/kakaoPay/application/SinglePaymentService.java
  src/main/java/com/codenear/butterfly/member/domain/Member.java
Labels: 🚀 Feat

#202 199 feat 마케팅 수신 동의 변동 및 저장 추가
  src/main/java/com/codenear/butterfly/consent/application/ConsentService.java
  src/main/java/com/codenear/butterfly/consent/domain/Consent.java
  src/main/java/com/codenear/butterfly/consent/dto/ConsentUpdateRequestDTO.java
  src/main/java/com/codenear/butterfly/consent/presentation/ConsentController.java
  src/main/java/com/codenear/butterfly/consent/presentation/ConsentControllerSwagger.java
  src/main/java/com/codenear/butterfly/global/exception/GlobalExceptionHandler.java
Labels: 🚀 Feat

#205 refactor: 수신 동의 명칭 변경 (#203)
  src/main/java/com/codenear/butterfly/consent/domain/ConsentType.java
Labels: 🛠️ Refactor

#208 200 상품 구매 요청 dto 수정
  src/main/java/com/codenear/butterfly/global/exception/ErrorCode.java
  src/main/java/com/codenear/butterfly/kakaoPay/application/SinglePaymentService.java
  src/main/java/com/codenear/butterfly/kakaoPay/domain/Amount.java
  src/main/java/com/codenear/butterfly/kakaoPay/domain/CardInfo.java
  src/main/java/com/codenear/butterfly/kakaoPay/domain/OrderDetails.java
  src/main/java/com/codenear/butterfly/kakaoPay/domain/dto/OrderType.java
  src/main/java/com/codenear/butterfly/kakaoPay/domain/dto/PaymentRequestDTO.java
  src/main/java/com/codenear/butterfly/kakaoPay/domain/dto/kakao/ReadyResponseDTO.java
  src/main/java/com/codenear/butterfly/kakaoPay/domain/repository/OrderDetailsRepository.java
Labels: 🛠️ Refactor

#209 207 로그아웃 기능 추가
  src/main/java/com/codenear/butterfly/auth/domain/JwtRefreshRepository.java
  src/main/java/com/codenear/butterfly/auth/presentation/CustomLogoutHandler.java
  src/main/java/com/codenear/butterfly/auth/presentation/CustomLogoutSuccessHandler.java
  src/main/java/com/codenear/butterfly/global/config/SecurityConfig.java
  src/main/java/com/codenear/butterfly/global/filter/JwtFilter.java
Labels: 🚀 Feat

#211 210 카카오페이 단건결제 api swagger 리팩토링
  src/main/java/com/codenear/butterfly/kakaoPay/application/SinglePaymentService.java
  src/main/java/com/codenear/butterfly/kakaoPay/domain/dto/BasePaymentRequestDTO.java
  src/main/java/com/codenear/butterfly/kakaoPay/domain/dto/DeliveryPaymentRequestDTO.java
  src/main/java/com/codenear/butterfly/kakaoPay/domain/dto/PaymentRequestDTO.java
  src/main/java/com/codenear/butterfly/kakaoPay/domain/dto/PickupPaymentRequestDTO.java
  src/main/java/com/codenear/butterfly/kakaoPay/presentation/SinglePayController.java
  src/main/java/com/codenear/butterfly/kakaoPay/presentation/SinglePayControllerSwagger.java
Labels: 🛠️ Refactor

#213 refactor: 결제 승인 시 ResponseDTO 반환
  src/main/java/com/codenear/butterfly/kakaoPay/presentation/SinglePayController.java
  src/main/java/com/codenear/butterfly/kakaoPay/presentation/SinglePayControllerSwagger.java
Labels: 🛠️ Refactor

#215 214 로그아웃 api 명세서
  src/main/java/com/codenear/butterfly/auth/presentation/LogoutController.java
  src/main/java/com/codenear/butterfly/auth/presentation/swagger/LogoutControllerSwagger.java
  src/main/java/com/codenear/butterfly/global/config/SwaggerConfig.java
Labels: 🚀 Feat

#217 216 feat code near 플랫폼 회원가입 시 마케팅 동의 추가
  src/main/java/com/codenear/butterfly/auth/application/email/EmailRegisterService.java
  src/main/java/com/codenear/butterfly/auth/domain/dto/AuthRegisterDTO.java
  src/main/java/com/codenear/butterfly/consent/application/ConsentService.java
Labels: 🚀 Feat

#219 feat: 메인 주소 여부 전송 데이터 추가 (#218)
  src/main/java/com/codenear/butterfly/address/application/AddressService.java
  src/main/java/com/codenear/butterfly/address/domain/dto/AddressResponseDTO.java
Labels: 🚀 Feat

#222 feat: 유저 정보 반환시, 전화번호 추가 (#221)
  src/main/java/com/codenear/butterfly/member/application/MemberService.java
  src/main/java/com/codenear/butterfly/member/domain/dto/MemberInfoDTO.java
Labels: 🚀 Feat

#224 223 유저 정보 저장 api 생성
  src/main/java/com/codenear/butterfly/global/exception/ErrorCode.java
  src/main/java/com/codenear/butterfly/member/application/NicknameService.java
  src/main/java/com/codenear/butterfly/member/application/ProfileService.java
  src/main/java/com/codenear/butterfly/member/domain/Member.java
  src/main/java/com/codenear/butterfly/member/domain/dto/ProfileUpdateRequestDTO.java
  src/main/java/com/codenear/butterfly/member/presentation/ProfileController.java
  src/main/java/com/codenear/butterfly/member/presentation/swagger/ProfileControllerSwagger.java
Labels: 🚀 Feat

#228 227 s3 config 설정 파일 삭제 기능 구현
  build.gradle
  src/main/java/com/codenear/butterfly/s3/application/S3Service.java
  src/main/java/com/codenear/butterfly/s3/config/S3Config.java
  src/main/java/com/codenear/butterfly/s3/domain/S3Directory.java
  src/main/java/com/codenear/butterfly/s3/exception/S3Exception.java
Labels: 🚀 Feat

#230 229 s3 파일 등록 기능 구현
  src/main/java/com/codenear/butterfly/s3/application/S3Service.java
  src/main/java/com/codenear/butterfly/s3/domain/S3Directory.java
  src/test/java/com/codenear/butterfly/s3/application/S3ServiceTest.java
Labels: 🚀 Feat

#231 225 사진 저장 기능 도입 후 정보 저장 추가
  src/main/java/com/codenear/butterfly/member/application/ProfileService.java
  src/main/java/com/codenear/butterfly/member/domain/Member.java
  src/main/java/com/codenear/butterfly/member/domain/dto/ProfileUpdateRequestDTO.java
  src/main/java/com/codenear/butterfly/member/presentation/ProfileController.java
  src/main/java/com/codenear/butterfly/member/presentation/swagger/ProfileControllerSwagger.java
  src/main/java/com/codenear/butterfly/s3/application/S3Service.java
Labels: 🚀 Feat, 🛠️ Refactor

#233 232 fix 주소 기능 관련 반환 데이터 수정
  src/main/java/com/codenear/butterfly/address/application/AddressService.java
  src/main/java/com/codenear/butterfly/address/domain/dto/AddressAddResponseDTO.java
  src/main/java/com/codenear/butterfly/address/presentation/AddressController.java
  src/main/java/com/codenear/butterfly/address/presentation/AddressControllerSwagger.java
Labels: 🐞 Bug, 🛠️ Refactor

#235 234 sms 기능
  build.gradle
  src/main/java/com/codenear/butterfly/sms/application/SmsService.java
  src/main/java/com/codenear/butterfly/sms/application/SmsServiceImpl.java
  src/main/java/com/codenear/butterfly/sms/config/SmsConfig.java
  src/test/java/com/codenear/butterfly/sms/application/SmsServiceTest.java
Labels: 🚀 Feat

#236 226 상품 결제 취소
  src/main/java/com/codenear/butterfly/kakaoPay/application/CancelPaymentService.java
  src/main/java/com/codenear/butterfly/kakaoPay/application/SinglePaymentService.java
  src/main/java/com/codenear/butterfly/kakaoPay/domain/CancelPayment.java
  src/main/java/com/codenear/butterfly/kakaoPay/domain/CanceledAmount.java
  src/main/java/com/codenear/butterfly/kakaoPay/domain/dto/ApproveRequestDTO.java
  src/main/java/com/codenear/butterfly/kakaoPay/domain/dto/CancelRequestDTO.java
  src/main/java/com/codenear/butterfly/kakaoPay/domain/dto/kakao/CancelResponseDTO.java
  src/main/java/com/codenear/butterfly/kakaoPay/domain/repository/CancelPaymentRepository.java
  src/main/java/com/codenear/butterfly/kakaoPay/presentation/cancelPayment/CancelPaymentController.java
  src/main/java/com/codenear/butterfly/kakaoPay/presentation/cancelPayment/CancelPaymentControllerSwagger.java
  src/main/java/com/codenear/butterfly/kakaoPay/presentation/singlepay/SinglePayController.java
  src/main/java/com/codenear/butterfly/kakaoPay/presentation/singlepay/SinglePayControllerSwagger.java
Labels: 🚀 Feat

#239 237 랜덤 6자리 생성 후 redis 저장 기능
  src/main/java/com/codenear/butterfly/certify/application/CertifyService.java
  src/main/java/com/codenear/butterfly/certify/application/CertifyValidator.java
  src/main/java/com/codenear/butterfly/certify/dto/CertifyRequestDTO.java
  src/main/java/com/codenear/butterfly/certify/presentation/CertifyController.java
  src/main/java/com/codenear/butterfly/certify/presentation/CertifyControllerSwagger.java
  src/main/java/com/codenear/butterfly/global/config/SwaggerConfig.java
  src/main/java/com/codenear/butterfly/global/exception/ErrorCode.java
  src/main/java/com/codenear/butterfly/global/util/RandomUtil.java
  src/main/java/com/codenear/butterfly/member/application/MemberService.java
  src/main/java/com/codenear/butterfly/member/domain/Member.java
  src/test/java/com/codenear/butterfly/global/util/RandomUtilTest.java
  src/test/java/com/codenear/butterfly/sms/application/SmsServiceTest.java
Labels: 🚀 Feat

#245 refactor(AddressService): 주소 상세 값 반환 변경 (#244)
  src/main/java/com/codenear/butterfly/address/application/AddressService.java
Labels: 🐞 Bug

#242 241 프로필 수정 로직 수정
  src/main/java/com/codenear/butterfly/member/application/MemberService.java
  src/main/java/com/codenear/butterfly/member/application/NicknameService.java
  src/main/java/com/codenear/butterfly/member/application/ProfileService.java
  src/main/java/com/codenear/butterfly/member/domain/Member.java
  src/main/java/com/codenear/butterfly/member/domain/repository/member/MemberRepository.java
Labels: 🐞 Bug

#247 246 refactor 휴대폰 인증 문자 내용 변경
  src/main/java/com/codenear/butterfly/certify/application/CertifyService.java
  src/main/java/com/codenear/butterfly/certify/domain/CertifyMessage.java
  src/main/java/com/codenear/butterfly/certify/domain/dto/CertifyRequestDTO.java
  src/main/java/com/codenear/butterfly/certify/presentation/CertifyController.java
  src/main/java/com/codenear/butterfly/certify/presentation/CertifyControllerSwagger.java
Labels: 🚀 Feat

#248 238 상품 결제 완료 시 결과 반환 로직 리팩토링
  src/main/java/com/codenear/butterfly/global/exception/ErrorCode.java
  src/main/java/com/codenear/butterfly/kakaoPay/application/SinglePaymentService.java
  src/main/java/com/codenear/butterfly/kakaoPay/presentation/singlepay/SinglePayController.java
  src/main/java/com/codenear/butterfly/kakaoPay/presentation/singlepay/SinglePayControllerSwagger.java
Labels: 🚀 Feat, 🛠️ Refactor

#250 249 주문 내역 조회 api
  src/main/java/com/codenear/butterfly/kakaoPay/application/OrderDetailsService.java
  src/main/java/com/codenear/butterfly/kakaoPay/application/SinglePaymentService.java
  src/main/java/com/codenear/butterfly/kakaoPay/domain/OrderDetails.java
  src/main/java/com/codenear/butterfly/kakaoPay/domain/dto/BasePaymentRequestDTO.java
  src/main/java/com/codenear/butterfly/kakaoPay/domain/dto/order/OrderDetailsDTO.java
  src/main/java/com/codenear/butterfly/kakaoPay/domain/repository/OrderDetailsRepository.java
  src/main/java/com/codenear/butterfly/kakaoPay/presentation/singlepay/SinglePayController.java
  src/main/java/com/codenear/butterfly/kakaoPay/presentation/singlepay/SinglePayControllerSwagger.java
  src/main/java/com/codenear/butterfly/product/domain/repository/ProductRepository.java
Labels: 🚀 Feat

#254 refactor: 카카오페이 모바일 다이렉트 링크 추가
  src/main/java/com/codenear/butterfly/kakaoPay/domain/dto/kakao/ReadyResponseDTO.java
Labels: 🛠️ Refactor

#256 255 refactor 주문 내역 리팩토링
  src/main/java/com/codenear/butterfly/kakaoPay/application/CancelPaymentService.java
  src/main/java/com/codenear/butterfly/kakaoPay/application/SinglePaymentService.java
  src/main/java/com/codenear/butterfly/kakaoPay/domain/dto/PaymentStatus.java
  src/main/java/com/codenear/butterfly/kakaoPay/domain/dto/request/ApproveRequestDTO.java
  src/main/java/com/codenear/butterfly/kakaoPay/domain/dto/request/BasePaymentRequestDTO.java
  src/main/java/com/codenear/butterfly/kakaoPay/domain/dto/request/CancelRequestDTO.java
  src/main/java/com/codenear/butterfly/kakaoPay/domain/dto/request/DeliveryPaymentRequestDTO.java
  src/main/java/com/codenear/butterfly/kakaoPay/domain/dto/request/PickupPaymentRequestDTO.java
  src/main/java/com/codenear/butterfly/kakaoPay/domain/repository/KakaoPaymentRedisRepository.java
  src/main/java/com/codenear/butterfly/kakaoPay/presentation/cancelPayment/CancelPaymentController.java
  src/main/java/com/codenear/butterfly/kakaoPay/presentation/cancelPayment/CancelPaymentControllerSwagger.java
  src/main/java/com/codenear/butterfly/kakaoPay/presentation/singlepay/SinglePayController.java
  src/main/java/com/codenear/butterfly/kakaoPay/presentation/singlepay/SinglePayControllerSwagger.java
Labels: 🛠️ Refactor

#258 252 메인 admin 페이지 생성
  src/main/java/com/codenear/butterfly/admin/AdminController.java
  src/main/resources/static/favicon.ico
  src/main/resources/templates/admin/support/inquiryList.html
  src/main/resources/templates/admin/support/inquiryModal.html
  src/main/resources/templates/adminDashboard.html
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/fragments/scripts.html
  src/main/resources/templates/fragments/sidebar.html
  src/main/resources/templates/index.html
Labels: 🚀 Feat
