Repository BUTTERFLY-CODE-NEAR/Butterfly_BE, pull requests merged in 2024-11, with the labels that each got.

#260 259 회원 admin 페이지 생성
  src/main/java/com/codenear/butterfly/admin/AdminController.java
  src/main/java/com/codenear/butterfly/admin/member/application/AdminMemberService.java
  src/main/java/com/codenear/butterfly/admin/member/presentation/AdminMemberController.java
  src/main/resources/templates/admin/member/member.html
  src/main/resources/templates/adminDashboard.html
  src/main/resources/templates/fragments/scripts.html
  src/main/resources/templates/fragments/sidebar.html
Labels: 🚀 Feat

#267 refactor: 상품 테이블 subtitle -> companyName으로 컬럼명 변경
  src/main/java/com/codenear/butterfly/product/application/FavoriteService.java
  src/main/java/com/codenear/butterfly/product/application/ProductViewService.java
  src/main/java/com/codenear/butterfly/product/domain/Product.java
  src/main/java/com/codenear/butterfly/product/domain/dto/OptionDTO.java
  src/main/java/com/codenear/butterfly/product/domain/dto/ProductDetailDTO.java
  src/main/java/com/codenear/butterfly/product/domain/dto/ProductViewDTO.java
Labels: 🛠️ Refactor

#270 269 geocoding 거리 계산 로직 추가
  src/main/java/com/codenear/butterfly/address/application/AddressService.java
  src/main/java/com/codenear/butterfly/address/domain/Address.java
  src/main/java/com/codenear/butterfly/geocoding/application/GeocodingClient.java
  src/main/java/com/codenear/butterfly/geocoding/application/GeocodingService.java
  src/main/java/com/codenear/butterfly/geocoding/application/GeocodingValidator.java
  src/main/java/com/codenear/butterfly/geocoding/exception/ErrorMessage.java
  src/test/java/com/codenear/butterfly/geocoding/application/GeocodingClientTest.java
  src/test/java/com/codenear/butterfly/geocoding/application/GeocodingServiceTest.java
Labels: 🚀 Feat

#272 refactor: 결제 완료 시 리다이렉트 url 변경
  src/main/java/com/codenear/butterfly/kakaoPay/presentation/singlepay/SinglePayController.java
  src/main/java/com/codenear/butterfly/kakaoPay/presentation/singlepay/SinglePayControllerSwagger.java
Labels: 🛠️ Refactor

#274 273 refactor 주문 상태 리팩토링
  src/main/java/com/codenear/butterfly/kakaoPay/application/SinglePaymentService.java
  src/main/java/com/codenear/butterfly/kakaoPay/domain/OrderDetails.java
  src/main/java/com/codenear/butterfly/kakaoPay/domain/dto/OrderStatus.java
  src/main/java/com/codenear/butterfly/kakaoPay/domain/dto/order/OrderDetailsDTO.java
  src/main/java/com/codenear/butterfly/kakaoPay/presentation/singlepay/SinglePayControllerSwagger.java
Labels: 🛠️ Refactor

#277 feat(FAQ): FAQ 관련 DB 생성 (#276)
  src/main/java/com/codenear/butterfly/support/domain/FAQ.java
Labels: 🚀 Feat

#280 279 feat 주문 상태에 주문 취소 status 추가
  src/main/java/com/codenear/butterfly/kakaoPay/application/CancelPaymentService.java
  src/main/java/com/codenear/butterfly/kakaoPay/domain/dto/OrderStatus.java
Labels: 🚀 Feat

#281 278 질문 및 답변 등록 admin
  src/main/java/com/codenear/butterfly/admin/exception/AdminException.java
  src/main/java/com/codenear/butterfly/admin/support/application/FAQService.java
  src/main/java/com/codenear/butterfly/admin/support/domain/dto/FAQRequest.java
  src/main/java/com/codenear/butterfly/support/domain/FAQ.java
  src/main/java/com/codenear/butterfly/support/domain/FAQRepository.java
  src/test/java/com/codenear/butterfly/admin/support/application/FAQServiceTest.java
Labels: 🚀 Feat

#285 284 faq 조회 api 추가
  src/main/java/com/codenear/butterfly/admin/support/application/FAQAdminService.java
  src/main/java/com/codenear/butterfly/admin/support/domain/dto/FAQAdminRequest.java
  src/main/java/com/codenear/butterfly/admin/support/presentation/FAQAdminController.java
  src/main/java/com/codenear/butterfly/support/application/FAQService.java
  src/main/java/com/codenear/butterfly/support/application/InquiryService.java
  src/main/java/com/codenear/butterfly/support/domain/FAQ.java
  src/main/java/com/codenear/butterfly/support/domain/dto/FAQResponse.java
  src/main/java/com/codenear/butterfly/support/domain/repositroy/FAQRepository.java
  src/main/java/com/codenear/butterfly/support/domain/repositroy/InquiryRepository.java
  src/main/java/com/codenear/butterfly/support/presentation/FAQController.java
  src/main/java/com/codenear/butterfly/support/presentation/InquiryController.java
  src/main/java/com/codenear/butterfly/support/presentation/swagger/FAQControllerSwagger.java
  src/main/java/com/codenear/butterfly/support/presentation/swagger/InquiryControllerSwagger.java
  src/test/java/com/codenear/butterfly/admin/support/application/FAQAdminServiceTest.java
  src/test/java/com/codenear/butterfly/support/application/FAQServiceTest.java
Labels: 🚀 Feat

#288 287 feat 상품 신청 인원에 따른 할인률 적용
  src/main/java/com/codenear/butterfly/kakaoPay/presentation/singlepay/SinglePayController.java
  src/main/java/com/codenear/butterfly/kakaoPay/presentation/singlepay/SinglePayControllerSwagger.java
  src/main/java/com/codenear/butterfly/member/domain/Member.java
  src/main/java/com/codenear/butterfly/product/application/FavoriteService.java
  src/main/java/com/codenear/butterfly/product/application/ProductViewService.java
  src/main/java/com/codenear/butterfly/product/domain/DiscountRate.java
  src/main/java/com/codenear/butterfly/product/domain/Option.java
  src/main/java/com/codenear/butterfly/product/domain/Price.java
  src/main/java/com/codenear/butterfly/product/domain/Product.java
  src/main/java/com/codenear/butterfly/product/util/ProductMapper.java
Labels: 🚀 Feat

#289 286 feat s3 이미지 업로드 리사이징
  build.gradle
  src/main/java/com/codenear/butterfly/global/exception/ErrorCode.java
  src/main/java/com/codenear/butterfly/global/exception/GlobalExceptionHandler.java
  src/main/java/com/codenear/butterfly/member/application/ProfileService.java
  src/main/java/com/codenear/butterfly/member/util/CustomMultipartFile.java
  src/main/java/com/codenear/butterfly/member/util/ImageResizeUtil.java
  src/main/resources/application.properties
Labels: 🚀 Feat

#293 290 fix s3 프로필 이미지 미삭제 버그
  src/main/java/com/codenear/butterfly/member/application/MemberService.java
  src/main/java/com/codenear/butterfly/member/application/ProfileService.java
  src/main/java/com/codenear/butterfly/s3/application/S3Service.java
Labels: 🐞 Bug

#294 feat: 상품 목록 조회 api에 품절 여부 추가
  src/main/java/com/codenear/butterfly/product/domain/Product.java
  src/main/java/com/codenear/butterfly/product/domain/dto/ProductViewDTO.java
  src/main/java/com/codenear/butterfly/product/util/ProductMapper.java
Labels: 🚀 Feat

#303 feat(OrderDetailsService): 주문 내역 최신순 정렬(#296)
  src/main/java/com/codenear/butterfly/kakaoPay/application/OrderDetailsService.java
Labels: 🚀 Feat

#301 298 질문 목록 리스트 등록 날짜 정렬
  src/main/java/com/codenear/butterfly/admin/support/application/InquiryAdminService.java
  src/main/java/com/codenear/butterfly/admin/support/domain/dto/InquiresResponse.java
  src/main/java/com/codenear/butterfly/admin/support/domain/dto/InquiryDetailsResponse.java
  src/main/java/com/codenear/butterfly/global/exception/ErrorMessage.java
  src/main/java/com/codenear/butterfly/support/application/InquiryFacade.java
  src/main/java/com/codenear/butterfly/support/application/InquiryService.java
  src/main/java/com/codenear/butterfly/support/exception/SupportException.java
Labels: 🚀 Feat

#305 302 상태 및 답변 변경 기능과 삭제 기능 추가
  src/main/java/com/codenear/butterfly/admin/support/application/InquiryAdminService.java
  src/main/java/com/codenear/butterfly/admin/support/domain/dto/InquiryAnswerRequest.java
  src/main/java/com/codenear/butterfly/support/domain/Inquiry.java
Labels: 🚀 Feat

#307 306 기능 화면 개발
  src/main/java/com/codenear/butterfly/admin/support/domain/dto/InquiryDetailsResponse.java
  src/main/java/com/codenear/butterfly/admin/support/presentation/FAQAdminController.java
  src/main/java/com/codenear/butterfly/admin/support/presentation/InquiryAdminController.java
  src/main/java/com/codenear/butterfly/support/domain/Inquiry.java
  src/main/resources/templates/admin/support/faq-details.html
  src/main/resources/templates/admin/support/inquiry-details.html
  src/main/resources/templates/admin/support/inquiry.html
  src/main/resources/templates/fragments/sidebar.html
Labels: 🚀 Feat

#304 295 상품 관리자 페이지 화면 구성
  src/main/java/com/codenear/butterfly/admin/products/application/AdminProductService.java
  src/main/java/com/codenear/butterfly/admin/products/presentation/AdminProductsController.java
  src/main/java/com/codenear/butterfly/product/domain/Product.java
  src/main/resources/templates/admin/products/product-edit.html
  src/main/resources/templates/admin/products/product-list.html
Labels: 🚀 Feat

#309 308 refactor 질문 생성 과정 기본 메시지 로직 수정
  src/main/java/com/codenear/butterfly/support/application/InquiryService.java
  src/main/java/com/codenear/butterfly/support/domain/Inquiry.java
  src/main/java/com/codenear/butterfly/support/domain/dto/InquiryRegisterRequest.java
  src/main/java/com/codenear/butterfly/support/presentation/InquiryController.java
  src/main/java/com/codenear/butterfly/support/presentation/swagger/InquiryControllerSwagger.java
Labels: 🛠️ Refactor

#311 refactor: redirect URL butterfly 스킴 적용
  src/main/java/com/codenear/butterfly/kakaoPay/presentation/singlepay/SinglePayController.java
  src/main/java/com/codenear/butterfly/kakaoPay/presentation/singlepay/SinglePayControllerSwagger.java
Labels: 🛠️ Refactor

#314 fix: 불필요 파라미터 제거
  src/main/java/com/codenear/butterfly/kakaoPay/presentation/singlepay/SinglePayController.java
Labels: 🐞 Bug

#318 317 클라이언트 → 서버 토큰 전달 및 저장 기능
  build.gradle
  src/main/java/com/codenear/butterfly/consent/application/ConsentFacade.java
  src/main/java/com/codenear/butterfly/consent/application/ConsentService.java
  src/main/java/com/codenear/butterfly/consent/domain/ConsentType.java
  src/main/java/com/codenear/butterfly/fcm/application/FCMFacade.java
  src/main/java/com/codenear/butterfly/fcm/application/FCMService.java
  src/main/java/com/codenear/butterfly/fcm/config/FirebaseConfig.java
  src/main/java/com/codenear/butterfly/fcm/domain/FCM.java
  src/main/java/com/codenear/butterfly/fcm/domain/FCMRepository.java
  src/main/java/com/codenear/butterfly/fcm/presentation/FCMController.java
  src/main/java/com/codenear/butterfly/fcm/presentation/FCMControllerSwagger.java
  src/main/java/com/codenear/butterfly/global/config/SwaggerConfig.java
  src/main/java/com/codenear/butterfly/member/application/MemberFacade.java
Labels: 🚀 Feat

#322 321 feat 주소 배달비 추가
  src/main/java/com/codenear/butterfly/address/application/AddressService.java
  src/main/java/com/codenear/butterfly/address/domain/Address.java
  src/main/java/com/codenear/butterfly/address/domain/dto/AddressResponse.java
  src/main/java/com/codenear/butterfly/address/presentation/AddressControllerSwagger.java
Labels: 🚀 Feat

#324 323 상품 추가 페이지
  .gitignore
  src/main/java/com/codenear/butterfly/admin/products/application/AdminProductService.java
  src/main/java/com/codenear/butterfly/admin/products/dto/DiscountRateRequest.java
  src/main/java/com/codenear/butterfly/admin/products/dto/ProductCreateRequest.java
  src/main/java/com/codenear/butterfly/admin/products/dto/ProductEditResponse.java
  src/main/java/com/codenear/butterfly/admin/products/dto/ProductUpdateRequest.java
  src/main/java/com/codenear/butterfly/admin/products/presentation/AdminProductsController.java
  src/main/java/com/codenear/butterfly/product/domain/DiscountRate.java
  src/main/java/com/codenear/butterfly/product/domain/Keyword.java
  src/main/java/com/codenear/butterfly/product/domain/Product.java
  src/main/java/com/codenear/butterfly/product/domain/repository/KeywordRepository.java
  src/main/resources/templates/admin/products/product-create.html
  src/main/resources/templates/admin/products/product-edit.html
  src/main/resources/templates/admin/products/product-list.html
Labels: 🚀 Feat

#326 refactor: 카카오페이 결제 준비 응답 시 앱 스킴 반환
  src/main/java/com/codenear/butterfly/kakaoPay/application/SinglePaymentService.java
  src/main/java/com/codenear/butterfly/kakaoPay/domain/dto/kakao/ReadyResponseDTO.java
Labels: 🛠️ Refactor
