Repository BUTTERFLY-CODE-NEAR/Butterfly_BE, pull requests merged in 2024-12, with the labels that each got.

#328 327 특정 topic 푸시 알람 기능
  src/main/java/com/codenear/butterfly/fcm/application/FCMFacade.java
  src/main/java/com/codenear/butterfly/fcm/application/FCMMessageService.java
  src/main/java/com/codenear/butterfly/fcm/application/FCMTokenService.java
  src/main/java/com/codenear/butterfly/fcm/presentation/FCMController.java
  src/test/java/com/codenear/butterfly/fcm/application/FirebaseMessagingClientTest.java
Labels: 🚀 Feat

#333 332 feat 신상품 알림 추가
  src/main/java/com/codenear/butterfly/admin/products/application/AdminProductService.java
  src/main/java/com/codenear/butterfly/admin/products/presentation/AdminProductsController.java
  src/main/java/com/codenear/butterfly/admin/support/application/InquiryAdminService.java
  src/main/java/com/codenear/butterfly/fcm/application/FCMMessageService.java
  src/main/java/com/codenear/butterfly/fcm/domain/FCMMessageConstant.java
  src/main/resources/templates/admin/products/product-list.html
Labels: 🚀 Feat

#336 334 기존 동의 사항 변경될 시 토픽 변동 기능
  src/main/java/com/codenear/butterfly/consent/application/ConsentService.java
  src/main/java/com/codenear/butterfly/consent/domain/Consent.java
  src/main/java/com/codenear/butterfly/consent/domain/ConsentType.java
  src/main/java/com/codenear/butterfly/fcm/application/FCMFacade.java
  src/main/java/com/codenear/butterfly/fcm/application/FCMTokenService.java
Labels: 🚀 Feat

#338 337 동의 여부에 따라 전송 기능
  src/main/java/com/codenear/butterfly/fcm/application/FCMMessageService.java
  src/main/java/com/codenear/butterfly/fcm/domain/FCMMessageConstant.java
  src/test/java/com/codenear/butterfly/fcm/application/FCMMessageServiceTest.java
Labels: 🚀 Feat

#339 335 상품 주문 완료 시 참여율 재고 변화
  src/main/java/com/codenear/butterfly/admin/products/application/AdminProductService.java
  src/main/java/com/codenear/butterfly/global/exception/ErrorCode.java
  src/main/java/com/codenear/butterfly/kakaoPay/application/SinglePaymentService.java
  src/main/java/com/codenear/butterfly/product/domain/Product.java
Labels: 🚀 Feat

#341 340 fix 순환 참조 문제
  src/main/java/com/codenear/butterfly/auth/application/email/EmailRegisterService.java
  src/main/java/com/codenear/butterfly/consent/application/ConsentDataAccess.java
  src/main/java/com/codenear/butterfly/consent/application/ConsentFacade.java
  src/main/java/com/codenear/butterfly/consent/application/ConsentService.java
  src/main/java/com/codenear/butterfly/consent/application/ConsentUpdateService.java
  src/main/java/com/codenear/butterfly/consent/domain/Consent.java
  src/main/java/com/codenear/butterfly/consent/dto/ConsentUpdateRequest.java
  src/main/java/com/codenear/butterfly/consent/presentation/ConsentController.java
  src/main/java/com/codenear/butterfly/consent/presentation/ConsentControllerSwagger.java
  src/main/java/com/codenear/butterfly/fcm/application/FCMMessageService.java
  src/main/java/com/codenear/butterfly/fcm/application/FCMTokenService.java
  src/test/java/com/codenear/butterfly/fcm/application/FCMMessageServiceTest.java
Labels: 🐞 Bug

#343 342 fix 중복 전화 번호 에러 처리
  src/main/java/com/codenear/butterfly/certify/application/CertifyService.java
  src/main/java/com/codenear/butterfly/certify/application/CertifyValidator.java
  src/main/java/com/codenear/butterfly/certify/exception/CertifyException.java
  src/main/java/com/codenear/butterfly/global/exception/ErrorCode.java
  src/main/java/com/codenear/butterfly/member/domain/repository/member/MemberRepository.java
  src/main/java/com/codenear/butterfly/member/infrastructure/MemberDataAccess.java
Labels: 🐞 Bug

#349 348 주문 내역 저장 시 주소 저장 방식 변경
  src/main/java/com/codenear/butterfly/kakaoPay/application/SinglePaymentService.java
  src/main/java/com/codenear/butterfly/kakaoPay/domain/OrderDetails.java
Labels: 🛠️ Refactor

#347 refactor: 상품 도메인 수정 메서드 리팩토링
  src/main/java/com/codenear/butterfly/product/domain/Product.java
Labels: 🛠️ Refactor

#353 352 프로모션 적용 가능 여부 확인 기능
  src/main/java/com/codenear/butterfly/promotion/domain/PointPromotion.java
  src/main/java/com/codenear/butterfly/promotion/domain/Promotion.java
  src/test/java/com/codenear/butterfly/promotion/domain/PointPromotionTest.java
  src/test/java/com/codenear/butterfly/promotion/domain/PromotionTest.java
Labels: 🚀 Feat

#356 354 프로모션 중복 지급 확인 기능
  src/main/java/com/codenear/butterfly/promotion/domain/Recipient.java
  src/main/java/com/codenear/butterfly/promotion/domain/repository/RecipientRepository.java
  src/test/java/com/codenear/butterfly/promotion/domain/repository/RecipientRepositoryTest.java
Labels: 🚀 Feat

#358 350 상품 사진 수정 로직
  src/main/java/com/codenear/butterfly/admin/products/application/AdminProductService.java
  src/main/java/com/codenear/butterfly/admin/products/dto/ProductCreateRequest.java
  src/main/java/com/codenear/butterfly/admin/products/dto/ProductUpdateRequest.java
  src/main/java/com/codenear/butterfly/product/domain/Product.java
  src/main/java/com/codenear/butterfly/s3/domain/S3Directory.java
  src/main/resources/templates/admin/products/product-create.html
  src/main/resources/templates/admin/products/product-edit.html
Labels: 🚀 Feat

#359 357 프로모션 최종 비즈니즈 기능
  src/main/java/com/codenear/butterfly/fcm/domain/FCMMessageConstant.java
  src/main/java/com/codenear/butterfly/point/domain/Point.java
  src/main/java/com/codenear/butterfly/promotion/application/CitationPromotionService.java
  src/main/java/com/codenear/butterfly/promotion/application/PromotionDataAccess.java
  src/main/java/com/codenear/butterfly/promotion/domain/PointPromotion.java
  src/main/java/com/codenear/butterfly/promotion/domain/repository/PointPromotionRepository.java
  src/main/java/com/codenear/butterfly/promotion/exception/PromotionException.java
  src/test/java/com/codenear/butterfly/promotion/application/CitationPromotionServiceTest.java
  src/test/java/com/codenear/butterfly/promotion/domain/PointPromotionTest.java
Labels: 🚀 Feat

#363 355 상품 구입 후 추가 할인율 변동 시 포인트 반환
  src/main/java/com/codenear/butterfly/kakaoPay/application/SinglePaymentService.java
  src/main/java/com/codenear/butterfly/point/domain/PointRepository.java
  src/main/java/com/codenear/butterfly/product/domain/Price.java
  src/main/java/com/codenear/butterfly/product/domain/Product.java
Labels: 🚀 Feat

#365 364 refactor 상품 컬럼 추가
  src/main/java/com/codenear/butterfly/admin/products/application/AdminProductService.java
  src/main/java/com/codenear/butterfly/admin/products/dto/ProductCreateRequest.java
  src/main/java/com/codenear/butterfly/admin/products/dto/ProductUpdateRequest.java
  src/main/java/com/codenear/butterfly/product/domain/Product.java
  src/main/java/com/codenear/butterfly/product/domain/dto/ProductDetailDTO.java
  src/main/java/com/codenear/butterfly/product/util/ProductMapper.java
  src/main/resources/templates/admin/products/product-create.html
  src/main/resources/templates/admin/products/product-edit.html
Labels: 🚀 Feat, 🛠️ Refactor

#367 366 feat 상품 sold out시 하단 정렬
  src/main/java/com/codenear/butterfly/product/application/FavoriteService.java
  src/main/java/com/codenear/butterfly/product/application/ProductViewService.java
Labels: 🚀 Feat

#370 369 fix 상품 삭제 불가 오류
  src/main/java/com/codenear/butterfly/admin/products/application/AdminProductService.java
  src/main/java/com/codenear/butterfly/product/domain/repository/FavoriteRepository.java
Labels: 🐞 Bug

#373 372 데이터 필드 설계
  src/main/java/com/codenear/butterfly/admin/products/application/AdminProductService.java
  src/main/java/com/codenear/butterfly/admin/support/application/InquiryAdminService.java
  src/main/java/com/codenear/butterfly/consent/application/ConsentUpdateService.java
  src/main/java/com/codenear/butterfly/fcm/exception/FCMException.java
  src/main/java/com/codenear/butterfly/notify/exception/NotifyException.java
  src/main/java/com/codenear/butterfly/notify/fcm/application/FCMFacade.java
  src/main/java/com/codenear/butterfly/notify/fcm/application/FCMMessageService.java
  src/main/java/com/codenear/butterfly/notify/fcm/application/FCMTokenService.java
  src/main/java/com/codenear/butterfly/notify/fcm/domain/FCM.java
  src/main/java/com/codenear/butterfly/notify/fcm/domain/FCMMessageConstant.java
  src/main/java/com/codenear/butterfly/notify/fcm/infrastructure/FCMRepository.java
  src/main/java/com/codenear/butterfly/notify/fcm/infrastructure/FirebaseConfig.java
  src/main/java/com/codenear/butterfly/notify/fcm/infrastructure/FirebaseMessagingClient.java
  src/main/java/com/codenear/butterfly/notify/fcm/presentation/FCMController.java
  src/main/java/com/codenear/butterfly/notify/fcm/presentation/FCMControllerSwagger.java
  src/main/java/com/codenear/butterfly/promotion/application/PointPromotionService.java
  src/test/java/com/codenear/butterfly/notify/application/FCMMessageServiceTest.java
  src/test/java/com/codenear/butterfly/notify/application/FirebaseMessagingClientTest.java
  src/test/java/com/codenear/butterfly/promotion/application/PointPromotionServiceTest.java
Labels: 🛠️ Refactor

#375 374 feat admin 주문 내역 상태 현황 변경
  src/main/java/com/codenear/butterfly/admin/order/application/AdminOrderDetailsService.java
  src/main/java/com/codenear/butterfly/admin/order/exception/OrderException.java
  src/main/java/com/codenear/butterfly/admin/order/presentation/AdminOrderDetailsController.java
  src/main/java/com/codenear/butterfly/global/exception/ErrorCode.java
  src/main/java/com/codenear/butterfly/kakaoPay/domain/OrderDetails.java
  src/main/java/com/codenear/butterfly/kakaoPay/domain/dto/OrderStatus.java
  src/main/resources/templates/admin/order/order-details.html
Labels: 🚀 Feat

#378 377 알림 목록 api memberid
  src/main/java/com/codenear/butterfly/member/domain/Member.java
  src/main/java/com/codenear/butterfly/notify/alarm/application/AlarmService.java
  src/main/java/com/codenear/butterfly/notify/alarm/domain/Alarm.java
  src/main/java/com/codenear/butterfly/notify/alarm/domain/dto/AlarmResponse.java
  src/main/java/com/codenear/butterfly/notify/alarm/domain/dto/AlarmsResponse.java
  src/main/java/com/codenear/butterfly/notify/alarm/infrastructure/AlarmRepository.java
  src/test/java/com/codenear/butterfly/notify/alarm/application/AlarmServiceTest.java
Labels: 🚀 Feat

#381 380 알림 확인 후 새로운 알림 상태 변경
  src/main/java/com/codenear/butterfly/notify/alarm/application/AlarmService.java
  src/main/java/com/codenear/butterfly/notify/alarm/infrastructure/AlarmRepository.java
Labels: 🚀 Feat

#382 379 알림 목록 추가 기능
  src/main/java/com/codenear/butterfly/consent/application/ConsentFacade.java
  src/main/java/com/codenear/butterfly/consent/application/ConsentService.java
  src/main/java/com/codenear/butterfly/consent/application/ConsentUpdateService.java
  src/main/java/com/codenear/butterfly/consent/domain/ConsentRepository.java
  src/main/java/com/codenear/butterfly/consent/infrastructure/ConsentDataAccess.java
  src/main/java/com/codenear/butterfly/consent/infrastructure/ConsentRepository.java
  src/main/java/com/codenear/butterfly/notify/alarm/application/AlarmService.java
  src/main/java/com/codenear/butterfly/notify/fcm/application/FCMFacade.java
  src/main/java/com/codenear/butterfly/notify/fcm/application/FCMMessageService.java
  src/test/java/com/codenear/butterfly/notify/application/FCMMessageServiceTest.java
Labels: 🚀 Feat

#385 383 알림 목록 반환 api swagger 문서화
  src/main/java/com/codenear/butterfly/global/config/SwaggerConfig.java
  src/main/java/com/codenear/butterfly/notify/alarm/domain/dto/AlarmResponse.java
  src/main/java/com/codenear/butterfly/notify/alarm/domain/dto/AlarmsResponse.java
  src/main/java/com/codenear/butterfly/notify/alarm/presentation/AlarmController.java
  src/main/java/com/codenear/butterfly/notify/alarm/presentation/AlarmControllerSwagger.java
Labels: 🚀 Feat

#386 384 유저 정보에 새로운 알림 표시
  src/main/java/com/codenear/butterfly/member/application/MemberService.java
  src/main/java/com/codenear/butterfly/member/domain/dto/MemberInfoDTO.java
  src/main/java/com/codenear/butterfly/notify/alarm/infrastructure/AlarmRepository.java
Labels: 🚀 Feat

#388 387 refactor 상품 도메인 리팩토링
  src/main/java/com/codenear/butterfly/admin/products/application/AdminProductService.java
  src/main/java/com/codenear/butterfly/kakaoPay/application/SinglePaymentService.java
  src/main/java/com/codenear/butterfly/member/domain/Member.java
  src/main/java/com/codenear/butterfly/product/application/FavoriteService.java
  src/main/java/com/codenear/butterfly/product/application/ProductViewService.java
  src/main/java/com/codenear/butterfly/product/domain/Favorite.java
  src/main/java/com/codenear/butterfly/product/domain/Product.java
  src/main/java/com/codenear/butterfly/product/domain/ProductInventory.java
  src/main/java/com/codenear/butterfly/product/domain/repository/ProductInventoryRepository.java
  src/main/java/com/codenear/butterfly/product/domain/repository/ProductRepository.java
  src/main/java/com/codenear/butterfly/product/util/ProductMapper.java
Labels: 🛠️ Refactor

#390 refactor(ProductMapper): 상품 할인률 반환 시 추가할인률 적용
  src/main/java/com/codenear/butterfly/product/util/ProductMapper.java
Labels: 🛠️ Refactor

#392 391 fix 관리자 페이지 추가할인 구간 수정 오류
  src/main/java/com/codenear/butterfly/admin/products/application/AdminProductService.java
  src/main/java/com/codenear/butterfly/admin/products/presentation/AdminProductsController.java
  src/main/resources/templates/admin/products/product-edit.html
Labels: 🐞 Bug

#394 refactor(Keyword): 상품 추가 시 키워드 중복 허용
  src/main/java/com/codenear/butterfly/product/domain/Keyword.java
Labels: 🛠️ Refactor
