Repository BUTTERFLY-CODE-NEAR/Butterfly_BE, pull requests merged in 2024-09, with the labels that each got.

#14 feat: 공통으로 정의하는 생성, 업데이트 속성 클래스 (#13)
  src/main/java/com/codenear/butterfly/common/domain/BaseEntity.java
Labels: 🚀 Feat

#16 15 회원 공통 추상 클래스 생성
  src/main/java/com/codenear/butterfly/member/domain/Grade.java
  src/main/java/com/codenear/butterfly/member/domain/Member.java
  src/main/java/com/codenear/butterfly/member/domain/Platform.java
  src/main/java/com/codenear/butterfly/member/domain/repository/MemberRepository.java
Labels: 🚀 Feat

#17 12 feat 회원 entity 생성
  src/main/java/com/codenear/butterfly/common/domain/BaseEntity.java
  src/main/java/com/codenear/butterfly/member/domain/Grade.java
  src/main/java/com/codenear/butterfly/member/domain/Member.java
  src/main/java/com/codenear/butterfly/member/domain/Platform.java
  src/main/java/com/codenear/butterfly/member/domain/repository/MemberRepository.java
Labels: 🚀 Feat

#20 19 회원 가입 및 로그인 로직
  .gitignore
  src/main/java/com/codenear/butterfly/ButterflyApplication.java
  src/main/java/com/codenear/butterfly/auth/application/AuthService.java
  src/main/java/com/codenear/butterfly/auth/domain/dto/AuthRequestDTO.java
  src/main/java/com/codenear/butterfly/auth/presentation/AuthController.java
  src/main/java/com/codenear/butterfly/member/domain/Member.java
  src/main/java/com/codenear/butterfly/member/domain/repository/MemberRepository.java
  src/main/resources/application.properties
Labels: 🚀 Feat

#24 feat: 스프링 시큐리티 설정 화이트리스트 추가 (#23)
  src/main/java/com/codenear/butterfly/global/config/SecurityConfig.java
  src/main/java/com/codenear/butterfly/global/property/SecurityProperties.java
Labels: 🚀 Feat

#26 25 whitelist 설정 리팩토링 및 테스트코드 추가
  src/main/java/com/codenear/butterfly/global/config/SecurityConfig.java
  src/main/java/com/codenear/butterfly/global/property/SecurityProperties.java
  src/test/java/com/codenear/butterfly/global/property/SecurityPropertiesTest.java
Labels: 🛠️Refactor

#28 27 이메일 회원가입 로직 구현
  .gitignore
  src/main/java/com/codenear/butterfly/auth/application/AuthService.java
  src/main/java/com/codenear/butterfly/auth/application/CustomUserDetailsService.java
  src/main/java/com/codenear/butterfly/auth/application/ErrorMessageService.java
  src/main/java/com/codenear/butterfly/auth/domain/dto/AuthRequestDTO.java
  src/main/java/com/codenear/butterfly/auth/domain/dto/CustomUserDetails.java
  src/main/java/com/codenear/butterfly/auth/presentation/AuthController.java
  src/main/java/com/codenear/butterfly/global/config/SecurityConfig.java
  src/main/java/com/codenear/butterfly/member/domain/Member.java
  src/main/java/com/codenear/butterfly/member/domain/Role.java
  src/main/java/com/codenear/butterfly/member/domain/repository/MemberRepository.java
  src/test/java/com/codenear/butterfly/auth/application/CustomUserDetailsServiceTest.java
Labels: 🚀 Feat

#29 11 jwt 기초 설정
  build.gradle
  src/main/java/com/codenear/butterfly/auth/application/OAuthService.java
  src/main/java/com/codenear/butterfly/auth/domain/dto/OAuthRequestDTO.java
  src/main/java/com/codenear/butterfly/auth/jwt/JwtFilter.java
  src/main/java/com/codenear/butterfly/auth/jwt/JwtUtil.java
  src/main/java/com/codenear/butterfly/auth/presentation/AuthController.java
  src/main/java/com/codenear/butterfly/auth/presentation/OAuthController.java
  src/main/java/com/codenear/butterfly/global/config/CorsConfig.java
  src/main/java/com/codenear/butterfly/global/config/OSecurityConfig.java
  src/main/java/com/codenear/butterfly/global/config/SecurityConfig.java
  src/main/java/com/codenear/butterfly/global/property/SecurityProperties.java
  src/main/resources/application.properties
  src/test/java/com/codenear/butterfly/global/property/SecurityPropertiesTest.java
Labels: 🚀 Feat

#30 9 feat 카카오톡 구글 oauth2 로그인 구현
  build.gradle
  src/main/java/com/codenear/butterfly/auth/application/AuthService.java
  src/main/java/com/codenear/butterfly/auth/domain/dto/AuthRequestDTO.java
  src/main/java/com/codenear/butterfly/auth/jwt/JwtFilter.java
  src/main/java/com/codenear/butterfly/auth/jwt/JwtUtil.java
  src/main/java/com/codenear/butterfly/auth/presentation/AuthController.java
  src/main/java/com/codenear/butterfly/global/config/CorsConfig.java
  src/main/java/com/codenear/butterfly/global/config/OSecurityConfig.java
  src/main/java/com/codenear/butterfly/global/config/SecurityConfig.java
  src/main/resources/application.properties
Labels: 🚀 Feat

#32 refactor: conflict 방지를 위해 클래스명 변경
  src/main/java/com/codenear/butterfly/auth/application/EmailRegisterService.java
  src/main/java/com/codenear/butterfly/auth/presentation/AuthController.java
  src/main/java/com/codenear/butterfly/global/config/SecurityConfig.java
Labels: 🛠️Refactor

#35 33 액세스 토큰 리프레쉬 토큰 추가
  src/main/java/com/codenear/butterfly/auth/application/AuthService.java
  src/main/java/com/codenear/butterfly/auth/application/jwt/JwtService.java
  src/main/java/com/codenear/butterfly/auth/domain/JwtRefresh.java
  src/main/java/com/codenear/butterfly/auth/domain/JwtRefreshRepository.java
  src/main/java/com/codenear/butterfly/auth/jwt/CookieUtil.java
  src/main/java/com/codenear/butterfly/auth/jwt/JwtFilter.java
  src/main/java/com/codenear/butterfly/auth/jwt/JwtUtil.java
  src/main/java/com/codenear/butterfly/auth/presentation/AuthController.java
  src/main/java/com/codenear/butterfly/global/config/OSecurityConfig.java
  src/main/java/com/codenear/butterfly/global/config/SecurityConfig.java
Labels: 🚀 Feat

#37 36 토큰 member 객체 email platform 데이터로 생성 변경
  src/main/java/com/codenear/butterfly/auth/application/AuthService.java
  src/main/java/com/codenear/butterfly/auth/domain/JwtRefresh.java
  src/main/java/com/codenear/butterfly/auth/jwt/JwtUtil.java
Labels: 🛠️Refactor

#39 38 로그인 관련 코드 리팩토링 진행 메소드 분할 service 레이어 분리 등
  src/main/java/com/codenear/butterfly/auth/application/jwt/JwtService.java
  src/main/java/com/codenear/butterfly/auth/application/jwt/TokenValidator.java
  src/main/java/com/codenear/butterfly/auth/presentation/AuthController.java
  src/main/java/com/codenear/butterfly/auth/presentation/JwtFilter.java
  src/main/java/com/codenear/butterfly/global/config/SecurityConfig.java
Labels: 🛠️Refactor

#40 31 로그인 로직 및 jwt 토큰 발급
  src/main/java/com/codenear/butterfly/auth/application/email/CustomUserDetailsService.java
  src/main/java/com/codenear/butterfly/auth/application/email/EmailLoginService.java
  src/main/java/com/codenear/butterfly/auth/application/email/EmailRegisterService.java
  src/main/java/com/codenear/butterfly/auth/domain/dto/CustomUserDetails.java
  src/main/java/com/codenear/butterfly/auth/presentation/AuthController.java
  src/main/java/com/codenear/butterfly/global/config/SecurityConfig.java
  src/main/java/com/codenear/butterfly/member/domain/Grade.java
  src/main/java/com/codenear/butterfly/member/domain/Member.java
  src/main/java/com/codenear/butterfly/member/domain/Role.java
  src/test/java/com/codenear/butterfly/auth/application/CustomUserDetailsServiceTest.java
Labels: 🚀 Feat

#42 41 fix platform 저장 안되는 오류 및 로그인시 이전 토큰 미삭제 버그
  src/main/java/com/codenear/butterfly/auth/application/jwt/JwtService.java
  src/main/java/com/codenear/butterfly/auth/domain/JwtRefresh.java
  src/main/java/com/codenear/butterfly/auth/domain/JwtRefreshRepository.java
Labels: 🐞 bug

#44 43 swagger api 명세서 작성
  src/main/java/com/codenear/butterfly/auth/domain/dto/AuthRequestDTO.java
  src/main/java/com/codenear/butterfly/auth/presentation/AuthController.java
  src/main/java/com/codenear/butterfly/auth/presentation/AuthControllerSwagger.java
  src/main/java/com/codenear/butterfly/global/config/SwaggerConfig.java
Labels: 🚀 Feat

#47 feat: 헬스 체크를 위한 actuator 엔드포인트 추가
  build.gradle
  src/main/resources/application.properties
Labels: 🚀 Feat, 💡 Chore

#49 chore: Jenkins 파일 설정
  .gitignore
  Jenkinsfile
Labels: 💡 Chore

#52 refactor: 플랫폼 검증 로직 리팩토링
  src/main/java/com/codenear/butterfly/auth/application/AuthService.java
  src/main/java/com/codenear/butterfly/auth/presentation/AuthController.java
Labels: 🛠️ Refactor

#54 refactor: 서비스 계층에서 로그 처리
  src/main/java/com/codenear/butterfly/auth/application/AuthService.java
  src/main/java/com/codenear/butterfly/auth/presentation/AuthController.java
Labels: 🛠️ Refactor

#57 56 refactor request dto 검증 로직 추가
  build.gradle
  src/main/java/com/codenear/butterfly/auth/domain/dto/AuthRequestDTO.java
  src/main/java/com/codenear/butterfly/auth/presentation/AuthController.java
  src/main/java/com/codenear/butterfly/global/exception/ValidationExceptionHandler.java
Labels: 🚀 Feat, 🛠️ Refactor, 💡 Chore

#58 55 refactor 중복 try catch 제거
  src/main/java/com/codenear/butterfly/auth/application/AuthService.java
  src/main/java/com/codenear/butterfly/auth/application/email/EmailLoginService.java
  src/main/java/com/codenear/butterfly/auth/application/email/EmailRegisterService.java
  src/main/java/com/codenear/butterfly/auth/exception/AuthExceptionHandler.java
  src/main/java/com/codenear/butterfly/auth/presentation/AuthController.java
Labels: 🚀 Feat, 🛠️ Refactor

#60 refactor: 메시지 처리 클래스 패키지 변경
  src/main/java/com/codenear/butterfly/auth/application/AuthService.java
  src/main/java/com/codenear/butterfly/auth/application/email/CustomUserDetailsService.java
  src/main/java/com/codenear/butterfly/auth/application/email/EmailLoginService.java
  src/main/java/com/codenear/butterfly/auth/exception/AuthExceptionHandler.java
  src/main/java/com/codenear/butterfly/auth/exception/message/MessageUtil.java
  src/main/java/com/codenear/butterfly/auth/presentation/AuthController.java
  src/test/java/com/codenear/butterfly/auth/application/CustomUserDetailsServiceTest.java
Labels: 🛠️ Refactor

#62 61 feat 회원 가입 및 로그인 검증 부분 추가
  src/main/java/com/codenear/butterfly/auth/domain/dto/AuthRequestDTO.java
  src/main/java/com/codenear/butterfly/auth/validator/PasswordValidator.java
  src/main/java/com/codenear/butterfly/auth/validator/ValidPassword.java
  src/main/java/com/codenear/butterfly/global/exception/ValidationExceptionHandler.java
  src/main/java/com/codenear/butterfly/member/domain/Platform.java
Labels: 🚀 Feat, 🛠️ Refactor

#64 63 feat 닉네임 생성 api
  .gitignore
  build.gradle
  src/main/java/com/codenear/butterfly/global/config/QuerydslConfig.java
  src/main/java/com/codenear/butterfly/member/application/NicknameService.java
  src/main/java/com/codenear/butterfly/member/domain/repository/MemberRepository.java
  src/main/java/com/codenear/butterfly/member/domain/repository/MemberRepositoryCustom.java
  src/main/java/com/codenear/butterfly/member/domain/repository/MemberRepositoryImpl.java
  src/main/java/com/codenear/butterfly/member/presentation/NicknameApi.java
  src/main/java/com/codenear/butterfly/member/util/KoreanCharacterRegex.java
Labels: 🚀 Feat

#70 69 refactor 닉네임 생성 로직 변경
  src/main/java/com/codenear/butterfly/member/application/NicknameService.java
  src/main/java/com/codenear/butterfly/member/util/KoreanCharacterRegex.java
  src/main/java/com/codenear/butterfly/member/util/NicknameList.java
Labels: 🚀 Feat, 🛠️ Refactor

#75 74 refactor jwt 코드 리팩토링 및 성능 향상 에러 처리
  src/main/java/com/codenear/butterfly/auth/jwt/JwtUtil.java
  src/main/java/com/codenear/butterfly/auth/presentation/JwtFilter.java
  src/main/java/com/codenear/butterfly/global/config/SecurityConfig.java
  src/main/java/com/codenear/butterfly/global/exception/ErrorCode.java
  src/main/java/com/codenear/butterfly/global/property/SecurityProperties.java
  src/main/java/com/codenear/butterfly/global/util/ResponseUtil.java
Labels: 🚀 Feat, 🛠️ Refactor

#78 77 feat 비즈니스 공통 클래스 정의
  src/main/java/com/codenear/butterfly/auth/exception/AuthException.java
  src/main/java/com/codenear/butterfly/global/exception/BusinessBaseException.java
  src/main/java/com/codenear/butterfly/global/exception/GlobalExceptionHandler.java
Labels: 🚀 Feat

#80 79 refactor auth 도메인 인증 처리 변환
  src/main/java/com/codenear/butterfly/auth/application/jwt/TokenValidator.java
  src/main/java/com/codenear/butterfly/auth/presentation/JwtFilter.java
  src/main/java/com/codenear/butterfly/global/exception/ErrorCode.java
  src/main/java/com/codenear/butterfly/global/util/ResponseUtil.java
Labels: 🛠️ Refactor

#82 81 refactor 쿠키 null 에러 처리 및 auth 컨트롤러 리팩토링
  src/main/java/com/codenear/butterfly/auth/jwt/CookieUtil.java
  src/main/java/com/codenear/butterfly/auth/presentation/AuthController.java
  src/main/java/com/codenear/butterfly/auth/presentation/AuthControllerSwagger.java
  src/main/java/com/codenear/butterfly/test/TestController.java
Labels: 🛠️ Refactor

#83 76 닉네임 생성 로직 예외 처리
  src/main/java/com/codenear/butterfly/global/exception/ErrorCode.java
  src/main/java/com/codenear/butterfly/member/application/NicknameService.java
  src/main/java/com/codenear/butterfly/member/exception/MemberException.java
Labels: 🚀 Feat, 🛠️ Refactor

#85 커스텀 예외 처리 적용
  src/main/java/com/codenear/butterfly/auth/application/AuthService.java
  src/main/java/com/codenear/butterfly/auth/application/email/CustomUserDetailsService.java
  src/main/java/com/codenear/butterfly/auth/application/email/EmailLoginService.java
  src/main/java/com/codenear/butterfly/auth/application/email/EmailRegisterService.java
  src/main/java/com/codenear/butterfly/auth/domain/dto/AuthRequestDTO.java
  src/main/java/com/codenear/butterfly/auth/exception/AuthExceptionHandler.java
  src/main/java/com/codenear/butterfly/auth/presentation/AuthController.java
  src/main/java/com/codenear/butterfly/global/exception/ErrorCode.java
  src/main/java/com/codenear/butterfly/global/util/MessageUtil.java
  src/main/java/com/codenear/butterfly/member/application/NicknameService.java
  src/test/java/com/codenear/butterfly/auth/application/CustomUserDetailsServiceTest.java
Labels: 🛠️ Refactor

#87 86 refactor 소셜 로그인 일반 로그인 초기 분리
  src/main/java/com/codenear/butterfly/auth/application/AuthService.java
  src/main/java/com/codenear/butterfly/auth/application/OauthService.java
  src/main/java/com/codenear/butterfly/auth/application/jwt/JwtService.java
  src/main/java/com/codenear/butterfly/auth/application/jwt/TokenValidator.java
  src/main/java/com/codenear/butterfly/auth/presentation/JwtFilter.java
  src/main/java/com/codenear/butterfly/auth/presentation/OauthController.java
  src/main/java/com/codenear/butterfly/auth/util/CookieUtil.java
  src/main/java/com/codenear/butterfly/auth/util/JwtUtil.java
  src/main/java/com/codenear/butterfly/global/config/SecurityConfig.java
Labels: 🛠️ Refactor

#89 88 refactor 소셜 로그인 파트 분리 작업
  src/main/java/com/codenear/butterfly/auth/application/OauthService.java
  src/main/java/com/codenear/butterfly/auth/domain/dto/OauthDTO.java
  src/main/java/com/codenear/butterfly/auth/presentation/OauthController.java
  src/main/java/com/codenear/butterfly/global/util/ResponseUtil.java
  src/main/java/com/codenear/butterfly/member/domain/repository/MemberRepository.java
Labels: 🛠️ Refactor

#90 84 feat 회원가입 시 닉네임 필터링
  .gitignore
  src/main/java/com/codenear/butterfly/auth/application/AuthService.java
  src/main/java/com/codenear/butterfly/auth/application/OauthService.java
  src/main/java/com/codenear/butterfly/auth/application/email/CustomUserDetailsService.java
  src/main/java/com/codenear/butterfly/auth/application/email/EmailRegisterService.java
  src/main/java/com/codenear/butterfly/global/exception/ErrorCode.java
  src/main/java/com/codenear/butterfly/member/application/.DS_Store
  src/main/java/com/codenear/butterfly/member/application/NicknameService.java
  src/main/java/com/codenear/butterfly/member/domain/ForbiddenWord.java
  src/main/java/com/codenear/butterfly/member/domain/repository/member/MemberRepository.java
  src/main/java/com/codenear/butterfly/member/domain/repository/member/MemberRepositoryCustom.java
  src/main/java/com/codenear/butterfly/member/domain/repository/member/MemberRepositoryImpl.java
  src/main/java/com/codenear/butterfly/member/domain/repository/nickname/ForbiddenWordRepository.java
  src/main/java/com/codenear/butterfly/member/presentation/NicknameApi.java
  src/main/java/com/codenear/butterfly/member/util/ForbiddenWordFilter.java
  src/test/java/com/codenear/butterfly/auth/application/CustomUserDetailsServiceTest.java
Labels: 🚀 Feat

#92 91 feat refactor oauth 컨트롤러 swagger 적용
  src/main/java/com/codenear/butterfly/auth/domain/dto/OauthDTO.java
  src/main/java/com/codenear/butterfly/auth/presentation/OauthController.java
  src/main/java/com/codenear/butterfly/auth/presentation/OauthControllerSwagger.java
  src/main/java/com/codenear/butterfly/global/config/SwaggerConfig.java
Labels: 🚀 Feat, 🛠️ Refactor

#94 refactor: Global 예외 핸들러에 체크, 언체크 예외 추가 (#93)
  src/main/java/com/codenear/butterfly/global/exception/GlobalExceptionHandler.java
Labels: 🛠️ Refactor

#96 95 refactor 유지보수를 계층에 알맞는 파일 이동
  src/main/java/com/codenear/butterfly/auth/application/AuthService.java
  src/main/java/com/codenear/butterfly/auth/application/JwtService.java
  src/main/java/com/codenear/butterfly/auth/application/OauthService.java
  src/main/java/com/codenear/butterfly/auth/application/validator/TokenValidator.java
  src/main/java/com/codenear/butterfly/auth/presentation/AuthController.java
  src/main/java/com/codenear/butterfly/auth/presentation/OauthController.java
  src/main/java/com/codenear/butterfly/auth/presentation/swagger/AuthControllerSwagger.java
  src/main/java/com/codenear/butterfly/auth/presentation/swagger/OauthControllerSwagger.java
  src/main/java/com/codenear/butterfly/global/config/SecurityConfig.java
  src/main/java/com/codenear/butterfly/global/filter/JwtFilter.java
Labels: 🛠️ Refactor

#98 97 refactor 개인 소셜 dto 분리 작업
  src/main/java/com/codenear/butterfly/auth/application/AuthService.java
  src/main/java/com/codenear/butterfly/auth/application/email/EmailRegisterService.java
  src/main/java/com/codenear/butterfly/auth/domain/dto/AuthLoginDTO.java
  src/main/java/com/codenear/butterfly/auth/domain/dto/AuthRegisterDTO.java
  src/main/java/com/codenear/butterfly/auth/presentation/AuthController.java
  src/main/java/com/codenear/butterfly/auth/presentation/swagger/AuthControllerSwagger.java
  src/main/java/com/codenear/butterfly/auth/validator/PasswordValidator.java
Labels: 🛠️ Refactor

#101 100 refactor 개인 로그인 회원가입 swagger 수정
  src/main/java/com/codenear/butterfly/auth/application/AuthService.java
  src/main/java/com/codenear/butterfly/auth/application/email/EmailRegisterService.java
  src/main/java/com/codenear/butterfly/auth/domain/dto/AuthLoginDTO.java
  src/main/java/com/codenear/butterfly/auth/domain/dto/AuthRegisterDTO.java
  src/main/java/com/codenear/butterfly/auth/presentation/swagger/AuthControllerSwagger.java
Labels: 🛠️ Refactor

#102 99 refactor 커스텀 비밀번호 검증 어노테이션 수정
  src/main/java/com/codenear/butterfly/auth/annotation/PasswordValidator.java
  src/main/java/com/codenear/butterfly/auth/annotation/ValidPassword.java
  src/main/java/com/codenear/butterfly/auth/domain/dto/AuthRegisterDTO.java
  src/main/java/com/codenear/butterfly/global/exception/ErrorCode.java
  src/main/java/com/codenear/butterfly/global/exception/GlobalExceptionHandler.java
Labels: 🛠️ Refactor

#104 103 refactor 닉네임 response시애 객체 사용
  src/main/java/com/codenear/butterfly/auth/presentation/swagger/AuthControllerSwagger.java
  src/main/java/com/codenear/butterfly/global/exception/ErrorCode.java
  src/main/java/com/codenear/butterfly/member/application/NicknameService.java
  src/main/java/com/codenear/butterfly/member/domain/NicknameDTO.java
  src/main/java/com/codenear/butterfly/member/presentation/NicknameApi.java
  src/main/java/com/codenear/butterfly/member/presentation/NicknameController.java
  src/main/java/com/codenear/butterfly/member/presentation/NicknameControllerSwagger.java
Labels: 🛠️ Refactor

#106 105 feat 메인 마이페이지 유저 정보 api 추가
  src/main/java/com/codenear/butterfly/auth/application/OauthService.java
  src/main/java/com/codenear/butterfly/global/config/SwaggerConfig.java
  src/main/java/com/codenear/butterfly/global/exception/ErrorCode.java
  src/main/java/com/codenear/butterfly/member/application/MemberService.java
  src/main/java/com/codenear/butterfly/member/domain/dto/MemberInfoDTO.java
  src/main/java/com/codenear/butterfly/member/domain/repository/member/MemberRepository.java
  src/main/java/com/codenear/butterfly/member/presentation/MemberController.java
  src/main/java/com/codenear/butterfly/member/presentation/MemberControllerSwagger.java
Labels: 🚀 Feat, 🛠️ Refactor

#109 107 feat 메인 카테고리 상품 정보 api 추가
  src/main/java/com/codenear/butterfly/global/config/SwaggerConfig.java
  src/main/java/com/codenear/butterfly/global/exception/ErrorCode.java
  src/main/java/com/codenear/butterfly/product/application/ProductViewService.java
  src/main/java/com/codenear/butterfly/product/domain/Product.java
  src/main/java/com/codenear/butterfly/product/domain/dto/ProductViewDTO.java
  src/main/java/com/codenear/butterfly/product/domain/repository/ProductRepository.java
  src/main/java/com/codenear/butterfly/product/exception/ProductException.java
  src/main/java/com/codenear/butterfly/product/presentation/ProductController.java
  src/main/java/com/codenear/butterfly/product/presentation/ProductControllerSwagger.java
Labels: 🚀 Feat

#110 108 refactor member entity point 분리
  src/main/java/com/codenear/butterfly/auth/application/OauthService.java
  src/main/java/com/codenear/butterfly/auth/application/email/EmailRegisterService.java
  src/main/java/com/codenear/butterfly/member/application/MemberService.java
  src/main/java/com/codenear/butterfly/member/domain/Member.java
  src/main/java/com/codenear/butterfly/member/presentation/MemberController.java
  src/main/java/com/codenear/butterfly/member/presentation/NicknameController.java
  src/main/java/com/codenear/butterfly/member/presentation/swagger/MemberControllerSwagger.java
  src/main/java/com/codenear/butterfly/member/presentation/swagger/NicknameControllerSwagger.java
  src/main/java/com/codenear/butterfly/point/domain/Point.java
Labels: 🛠️ Refactor

#114 113 고객 문의 관리자 페이지 생성
  build.gradle
  src/main/resources/templates/admin/support/inquiryList.html
  src/main/resources/templates/admin/support/inquiryModal.html
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/index.html
Labels: 🚀 Feat, 🛠️ Refactor

#116 115 고객 문의 관련 도메인 정의
  src/main/java/com/codenear/butterfly/admin/support/presentation/AdminInquiryController.java
  src/main/java/com/codenear/butterfly/support/domain/Inquiry.java
  src/main/java/com/codenear/butterfly/support/domain/InquiryRepository.java
  src/main/java/com/codenear/butterfly/support/domain/InquiryStatus.java
  src/main/java/com/codenear/butterfly/support/domain/dto/InquiryListDTO.java
  src/main/java/com/codenear/butterfly/support/domain/dto/InquiryRegisterDTO.java
Labels: 🚀 Feat

#118 117 고객 문의 조회 발송 rest api 생성
  src/main/java/com/codenear/butterfly/global/config/SecurityConfig.java
  src/main/java/com/codenear/butterfly/support/application/InquiryService.java
  src/main/java/com/codenear/butterfly/support/presentation/InquiryController.java
Labels: 🚀 Feat

#122 121 refactor 유저 정보 등급 int 변경
  src/main/java/com/codenear/butterfly/member/application/MemberService.java
  src/main/java/com/codenear/butterfly/member/application/NicknameService.java
  src/main/java/com/codenear/butterfly/member/domain/Grade.java
Labels: 🛠️ Refactor

#124 refactor: 고객 문의 API Swagger 문서 작성 (#123)
  src/main/java/com/codenear/butterfly/global/config/SwaggerConfig.java
  src/main/java/com/codenear/butterfly/support/domain/dto/InquiryListDTO.java
  src/main/java/com/codenear/butterfly/support/domain/dto/InquiryRegisterDTO.java
  src/main/java/com/codenear/butterfly/support/presentation/InquiryController.java
  src/main/java/com/codenear/butterfly/support/presentation/InquiryControllerSwagger.java
Labels: 🚀 Feat

#128 127 최근 검색어 추가 및 조회 기능
  build.gradle
  src/main/java/com/codenear/butterfly/global/config/RedisConfig.java
  src/main/java/com/codenear/butterfly/search/application/SearchService.java
  src/main/java/com/codenear/butterfly/search/presentation/SearchController.java
Labels: 🚀 Feat

#130 feat: 최근 검색어 삭제 기능 API 추가 (#129)
  src/main/java/com/codenear/butterfly/search/presentation/SearchController.java
Labels: 🚀 Feat

#125 111 feat 카테고리 별 상품 조회 api 추가
  src/main/java/com/codenear/butterfly/product/application/CategoryService.java
  src/main/java/com/codenear/butterfly/product/application/ProductViewService.java
  src/main/java/com/codenear/butterfly/product/domain/Category.java
  src/main/java/com/codenear/butterfly/product/domain/Product.java
  src/main/java/com/codenear/butterfly/product/domain/repository/ProductRepository.java
  src/main/java/com/codenear/butterfly/product/presentation/ProductController.java
  src/main/java/com/codenear/butterfly/product/presentation/ProductControllerSwagger.java
  src/main/java/com/codenear/butterfly/product/util/CategoryConverter.java
Labels: 🚀 Feat

#132 131 연관 검색어 기능 추가
  src/main/java/com/codenear/butterfly/product/application/KeywordService.java
  src/main/java/com/codenear/butterfly/product/domain/Keyword.java
  src/main/java/com/codenear/butterfly/product/domain/Product.java
  src/main/java/com/codenear/butterfly/product/domain/repository/KeywordRepository.java
  src/main/java/com/codenear/butterfly/search/application/SearchService.java
  src/main/java/com/codenear/butterfly/search/presentation/SearchController.java
Labels: 🚀 Feat, 🛠️ Refactor

#138 회원가입 로직에 JWT 토큰 발급 추가 (#137)
  src/main/java/com/codenear/butterfly/auth/application/AuthService.java
  src/main/java/com/codenear/butterfly/auth/presentation/AuthController.java
  src/main/java/com/codenear/butterfly/auth/presentation/swagger/AuthControllerSwagger.java
Labels: 🚀 Feat

#136 135 api 명세서 추가
  src/main/java/com/codenear/butterfly/global/config/SwaggerConfig.java
  src/main/java/com/codenear/butterfly/search/presentation/SearchController.java
  src/main/java/com/codenear/butterfly/search/presentation/SearchControllerSwagger.java
Labels: 🚀 Feat

#141 SwaggerConfig 최적화 (#140)
  src/main/java/com/codenear/butterfly/global/config/SwaggerConfig.java
Labels: 🛠️ Refactor

#143 고객 문의 리스트 날짜 추가 (#142)
  src/main/java/com/codenear/butterfly/support/application/InquiryService.java
  src/main/java/com/codenear/butterfly/support/domain/dto/InquiryListDTO.java
Labels: 🐞 Bug

#139 feat: 전체 카테고리 및 일반 카테고리 api 분리
  src/main/java/com/codenear/butterfly/product/application/ProductViewService.java
  src/main/java/com/codenear/butterfly/product/presentation/ProductController.java
  src/main/java/com/codenear/butterfly/product/presentation/ProductControllerSwagger.java
Labels: 🚀 Feat

#146 검색어 부분 삭제 추가 (#145)
  src/main/java/com/codenear/butterfly/search/application/SearchService.java
  src/main/java/com/codenear/butterfly/search/presentation/SearchController.java
  src/main/java/com/codenear/butterfly/search/presentation/SearchControllerSwagger.java
Labels: 🚀 Feat

#149 검색어 정렬 최근 거 우선 순위 변경 (#147)
  src/main/java/com/codenear/butterfly/search/application/SearchService.java
Labels: 🐞 Bug

#151 고객 문의 리스트 최신 날짜 우선 순위 반환 (#150)
  src/main/java/com/codenear/butterfly/support/application/InquiryService.java
  src/main/java/com/codenear/butterfly/support/domain/InquiryRepository.java
Labels: 🐞 Bug

#154 153 찜 목록 기능 추가
  src/main/java/com/codenear/butterfly/auth/domain/dto/CustomUserDetails.java
  src/main/java/com/codenear/butterfly/global/exception/ErrorCode.java
  src/main/java/com/codenear/butterfly/member/domain/Member.java
  src/main/java/com/codenear/butterfly/member/domain/repository/member/MemberRepository.java
  src/main/java/com/codenear/butterfly/member/domain/repository/nickname/ForbiddenWordRepository.java
  src/main/java/com/codenear/butterfly/product/application/FavoriteService.java
  src/main/java/com/codenear/butterfly/product/application/ProductViewService.java
  src/main/java/com/codenear/butterfly/product/domain/Favorite.java
  src/main/java/com/codenear/butterfly/product/domain/dto/ProductViewDTO.java
  src/main/java/com/codenear/butterfly/product/domain/repository/FavoriteRepository.java
  src/main/java/com/codenear/butterfly/product/presentation/ProductController.java
  src/main/java/com/codenear/butterfly/product/presentation/ProductControllerSwagger.java
Labels: 🚀 Feat
