Repository BUTTERFLY-CODE-NEAR/Butterfly_BE, pull requests merged in 2025-02, with the labels that each got.

#406 397 feat 아이디 비밀번호 찾기
  src/main/java/com/codenear/butterfly/global/config/SwaggerConfig.java
  src/main/java/com/codenear/butterfly/member/domain/dto/ResetPasswordRequestDTO.java
  src/main/java/com/codenear/butterfly/member/domain/dto/VerifyFindPasswordRequestDTO.java
  src/main/java/com/codenear/butterfly/member/presentation/swagger/CredentialControllerSwagger.java
Labels: 🚀 Feat

#409 407 feat 컬럼 추가 신청 현황 게이지 배송 정보 상품 설명 이미지 및 리팩토링
  src/main/java/com/codenear/butterfly/admin/products/application/AdminProductService.java
  src/main/java/com/codenear/butterfly/admin/products/dto/ProductCreateRequest.java
  src/main/java/com/codenear/butterfly/admin/products/dto/ProductUpdateRequest.java
  src/main/java/com/codenear/butterfly/product/application/FavoriteService.java
  src/main/java/com/codenear/butterfly/product/application/ProductViewService.java
  src/main/java/com/codenear/butterfly/product/domain/Product.java
  src/main/java/com/codenear/butterfly/product/domain/ProductInventory.java
  src/main/java/com/codenear/butterfly/product/domain/dto/OptionDTO.java
  src/main/java/com/codenear/butterfly/product/domain/dto/ProductDetailDTO.java
  src/main/java/com/codenear/butterfly/product/domain/dto/ProductViewDTO.java
  src/main/java/com/codenear/butterfly/product/util/ProductMapper.java
  src/main/resources/templates/admin/products/product-create.html
  src/main/resources/templates/admin/products/product-edit.html
Labels: 🚀 Feat, 🛠️ Refactor

#405 404 feat 전체 알림 미확인 알림 개수 기능
  src/main/java/com/codenear/butterfly/admin/products/application/AdminProductService.java
  src/main/java/com/codenear/butterfly/kakaoPay/domain/repository/KakaoPaymentRedisRepository.java
  src/main/java/com/codenear/butterfly/notify/alarm/application/AlarmService.java
  src/main/java/com/codenear/butterfly/notify/alarm/domain/Alarm.java
  src/main/java/com/codenear/butterfly/notify/alarm/domain/dto/AlarmCountResponseDTO.java
  src/main/java/com/codenear/butterfly/notify/alarm/infrastructure/AlarmRedisRepository.java
  src/main/java/com/codenear/butterfly/notify/alarm/presentation/AlarmController.java
  src/main/java/com/codenear/butterfly/notify/alarm/presentation/AlarmControllerSwagger.java
  src/main/java/com/codenear/butterfly/notify/fcm/application/FCMFacade.java
  src/test/java/com/codenear/butterfly/notify/alarm/application/AlarmServiceTest.java
Labels: 🚀 Feat

#410 Test : CertifyServiceTest,CredentialServiceTest 수정
  src/main/java/com/codenear/butterfly/member/domain/dto/ResetPasswordRequestDTO.java
  src/main/java/com/codenear/butterfly/member/domain/dto/VerifyFindPasswordRequestDTO.java
  src/test/java/com/codenear/butterfly/certify/application/CertifyServiceTest.java
  src/test/java/com/codenear/butterfly/member/application/CredentialServiceTests.java
Labels: 🐞 Bug

#412 411 fix 알림 저장 시 isnew컬럼 false오류 수정
  src/main/java/com/codenear/butterfly/notify/alarm/application/AlarmService.java
  src/main/java/com/codenear/butterfly/notify/alarm/domain/Alarm.java
Labels: 🐞 Bug

#415 [Fix] 테스트코드 오류 수정
  .gitignore
  src/main/java/com/codenear/butterfly/notify/alarm/application/AlarmService.java
  src/main/java/com/codenear/butterfly/notify/alarm/domain/Alarm.java
  src/test/java/com/codenear/butterfly/geocoding/application/GeocodingClientTest.java
  src/test/java/com/codenear/butterfly/geocoding/application/GeocodingServiceTest.java
  src/test/java/com/codenear/butterfly/notify/application/FCMMessageServiceTest.java
Labels: 🐞 Bug

#417 Fix : 이메일로 비밀번호 찾기 로직 수정
  src/main/java/com/codenear/butterfly/global/exception/ErrorCode.java
  src/main/java/com/codenear/butterfly/member/application/CredentialService.java
  src/main/java/com/codenear/butterfly/member/domain/dto/FindPasswordRequestDTO.java
  src/main/java/com/codenear/butterfly/member/domain/dto/ResetPasswordRequestDTO.java
  src/main/java/com/codenear/butterfly/member/domain/dto/VerifyFindPasswordRequestDTO.java
  src/main/java/com/codenear/butterfly/member/domain/repository/member/MemberRepository.java
  src/main/java/com/codenear/butterfly/member/presentation/swagger/CredentialControllerSwagger.java
  src/test/java/com/codenear/butterfly/member/application/CredentialServiceTest.java
  src/test/java/com/codenear/butterfly/member/application/CredentialServiceTests.java
Labels: 🐞 Bug

#418 416 fix 상품 재고 오류 수정
  build.gradle
  src/main/java/com/codenear/butterfly/admin/products/application/AdminProductService.java
  src/main/java/com/codenear/butterfly/global/config/RabbitMQConfig.java
  src/main/java/com/codenear/butterfly/kakaoPay/application/CancelPaymentService.java
  src/main/java/com/codenear/butterfly/kakaoPay/application/SinglePaymentService.java
  src/main/java/com/codenear/butterfly/kakaoPay/domain/dto/rabbitmq/InventoryDecreaseMessageDTO.java
  src/main/java/com/codenear/butterfly/kakaoPay/domain/dto/rabbitmq/InventoryIncreaseMessageDTO.java
  src/main/java/com/codenear/butterfly/kakaoPay/domain/repository/KakaoPaymentRedisRepository.java
  src/main/java/com/codenear/butterfly/kakaoPay/util/KakaoPayRabbitMQConsumer.java
  src/main/java/com/codenear/butterfly/kakaoPay/util/KakaoPayRabbitMQProducer.java
  src/main/java/com/codenear/butterfly/product/domain/ProductInventory.java
Labels: 🐞 Bug, 🚀 Feat, 🛠️ Refactor

#420 419 fix 카카오페이 결제 오류 수정
  src/main/java/com/codenear/butterfly/kakaoPay/application/SinglePaymentService.java
  src/main/java/com/codenear/butterfly/kakaoPay/domain/dto/order/OrderDTO.java
  src/main/java/com/codenear/butterfly/kakaoPay/domain/repository/KakaoPaymentRedisRepository.java
  src/main/java/com/codenear/butterfly/kakaoPay/presentation/singlepay/SinglePayController.java
  src/main/java/com/codenear/butterfly/kakaoPay/presentation/singlepay/SinglePayControllerSwagger.java
  src/main/java/com/codenear/butterfly/kakaoPay/util/KakaoPaymentUtil.java
Labels: 🐞 Bug

#422 refactor(RedisConfig): redis 비밀번호 설정
  src/main/java/com/codenear/butterfly/global/config/RedisConfig.java
Labels: 🛠️ Refactor

#424 fix(SinglePaymentService): 재고 확인 오류 수정
  src/main/java/com/codenear/butterfly/kakaoPay/application/SinglePaymentService.java
  src/main/java/com/codenear/butterfly/kakaoPay/domain/repository/KakaoPaymentRedisRepository.java
Labels: 🐞 Bug

#431 fix(S3Service): FileUrl 수정
  src/main/java/com/codenear/butterfly/s3/application/S3Service.java
Labels: 🐞 Bug

#429 427 fix 재고 예약 오류 수정
  src/main/java/com/codenear/butterfly/global/config/RedisConfig.java
  src/main/java/com/codenear/butterfly/kakaoPay/application/SinglePaymentService.java
  src/main/java/com/codenear/butterfly/kakaoPay/domain/KakaoPayRedisField.java
  src/main/java/com/codenear/butterfly/kakaoPay/domain/repository/KakaoPaymentRedisRepository.java
  src/main/java/com/codenear/butterfly/kakaoPay/presentation/singlepay/SinglePayController.java
  src/main/java/com/codenear/butterfly/kakaoPay/presentation/singlepay/SinglePayControllerSwagger.java
  src/main/java/com/codenear/butterfly/kakaoPay/util/KakaoPayRedisExpiredKeyListener.java
Labels: 🐞 Bug, 🚀 Feat

#426 425 feat 구간할인율 및 게이지 유동적 변경
  src/main/java/com/codenear/butterfly/admin/products/application/AdminProductService.java
  src/main/java/com/codenear/butterfly/kakaoPay/util/KakaoPayRabbitMQConsumer.java
  src/main/java/com/codenear/butterfly/product/domain/ProductInventory.java
  src/main/java/com/codenear/butterfly/product/domain/dto/ProductDetailDTO.java
  src/main/java/com/codenear/butterfly/product/domain/dto/ProductViewDTO.java
  src/main/java/com/codenear/butterfly/product/util/ProductMapper.java
  src/main/resources/templates/admin/products/product-create.html
  src/main/resources/templates/admin/products/product-edit.html
Labels: 🚀 Feat

#434 docs(SinglePayControllerSwagger): 결제 성공,취소,실패에 대한 Swagger 가시화
  src/main/java/com/codenear/butterfly/kakaoPay/presentation/singlepay/SinglePayControllerSwagger.java
Labels: documentation
