Repository BUTTERFLY-CODE-NEAR/Butterfly_BE, pull requests merged in 2025-01, with the labels that each got.

#398 395 fix sql 예약어 option 에러
  src/main/java/com/codenear/butterfly/product/domain/Option.java
  src/main/java/com/codenear/butterfly/s3/application/S3Service.java
  src/main/java/com/codenear/butterfly/s3/config/S3Config.java
Labels: 🐞 Bug, 🛠️ Refactor

#400 399 refactor 카카오 페이 단건결제 코드 리팩토링
  src/main/java/com/codenear/butterfly/admin/order/application/AdminOrderDetailsService.java
  src/main/java/com/codenear/butterfly/global/exception/ErrorCode.java
  src/main/java/com/codenear/butterfly/global/util/HashMapUtil.java
  src/main/java/com/codenear/butterfly/kakaoPay/application/CancelPaymentService.java
  src/main/java/com/codenear/butterfly/kakaoPay/application/SinglePaymentService.java
  src/main/java/com/codenear/butterfly/kakaoPay/domain/Amount.java
  src/main/java/com/codenear/butterfly/kakaoPay/domain/CancelPayment.java
  src/main/java/com/codenear/butterfly/kakaoPay/domain/CanceledAmount.java
  src/main/java/com/codenear/butterfly/kakaoPay/domain/CardInfo.java
  src/main/java/com/codenear/butterfly/kakaoPay/domain/KakaoPayRedisField.java
  src/main/java/com/codenear/butterfly/kakaoPay/domain/OrderDetails.java
  src/main/java/com/codenear/butterfly/kakaoPay/domain/PaymentMethod.java
  src/main/java/com/codenear/butterfly/kakaoPay/domain/SinglePayment.java
  src/main/java/com/codenear/butterfly/kakaoPay/domain/dto/request/PickupPaymentRequestDTO.java
  src/main/java/com/codenear/butterfly/kakaoPay/domain/repository/KakaoPaymentRedisRepository.java
  src/main/java/com/codenear/butterfly/kakaoPay/util/KakaoPaymentUtil.java
Labels: 🛠️ Refactor

#403 fix(S3Directory): S3 저장 디렉토리 변경 (#402)
  src/main/java/com/codenear/butterfly/s3/domain/S3Directory.java
Labels: 🐞 Bug

#401 397 feat 아이디 비밀번호 찾기
  .gitignore
  build.gradle
  src/main/java/com/codenear/butterfly/auth/annotation/PasswordValidator.java
  src/main/java/com/codenear/butterfly/certify/application/CertifyService.java
  src/main/java/com/codenear/butterfly/certify/domain/CertifyType.java
  src/main/java/com/codenear/butterfly/certify/domain/dto/CertifyRequest.java
  src/main/java/com/codenear/butterfly/global/config/SwaggerConfig.java
  src/main/java/com/codenear/butterfly/global/exception/ErrorCode.java
  src/main/java/com/codenear/butterfly/global/property/SecurityProperties.java
  src/main/java/com/codenear/butterfly/mail/application/MailService.java
  src/main/java/com/codenear/butterfly/mail/config/MailConfig.java
  src/main/java/com/codenear/butterfly/member/application/CredentialService.java
  src/main/java/com/codenear/butterfly/member/application/MemberService.java
  src/main/java/com/codenear/butterfly/member/domain/Member.java
  src/main/java/com/codenear/butterfly/member/domain/dto/FindPasswordRequestDTO.java
  src/main/java/com/codenear/butterfly/member/domain/dto/ResetPasswordRequestDTO.java
  src/main/java/com/codenear/butterfly/member/domain/dto/VerifyFindPasswordRequestDTO.java
  src/main/java/com/codenear/butterfly/member/domain/enums/VerificationType.java
  src/main/java/com/codenear/butterfly/member/domain/repository/member/MemberRepository.java
  src/main/java/com/codenear/butterfly/member/presentation/CredentialController.java
  src/main/java/com/codenear/butterfly/member/presentation/swagger/CredentialControllerSwagger.java
  src/test/java/com/codenear/butterfly/member/application/CredentialServiceTests.java
Labels: 🚀 Feat
